# Generated by Django 3.1.3 on 2021-01-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_name', models.CharField(max_length=50)),
                ('book_name', models.CharField(max_length=100)),
                ('pub_date', models.DateField(auto_now_add=True, null=True)),
                ('genre', models.CharField(choices=[('Science', 'Science'), ('History', 'History')], max_length=10)),
            ],
        ),
    ]
