# Generated by Django 3.1.3 on 2021-01-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='auth_name',
            new_name='name',
        ),
    ]
